# Generated by Django 5.0.6 on 2024-07-03 14:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("detectionApi", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="languages",
            field=models.CharField(default="eng+spa+fra+deu+ita+rus", max_length=100),
        ),
        migrations.AddField(
            model_name="post",
            name="mode",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="post",
            name="title",
            field=models.CharField(default="IMAGE", max_length=100),
        ),
    ]
